/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as GardenRouteImport } from './routes/garden'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as GardenIndexRouteImport } from './routes/garden.index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as GardenSlugRouteImport } from './routes/garden.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminProjectsNewRouteImport } from './routes/_authenticated/admin/projects/new'
import { Route as AuthenticatedAdminProjectsIdRouteImport } from './routes/_authenticated/admin/projects/$id'
import { Route as AuthenticatedAdminGardenNewRouteImport } from './routes/_authenticated/admin/garden/new'
import { Route as AuthenticatedAdminGardenIdRouteImport } from './routes/_authenticated/admin/garden/$id'

const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const GardenRoute = GardenRouteImport.update({
  id: '/garden',
  path: '/garden',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const GardenIndexRoute = GardenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GardenRoute,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjectsRoute,
} as any)
const GardenSlugRoute = GardenSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GardenRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminProjectsNewRoute =
  AuthenticatedAdminProjectsNewRouteImport.update({
    id: '/admin/projects/new',
    path: '/admin/projects/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminProjectsIdRoute =
  AuthenticatedAdminProjectsIdRouteImport.update({
    id: '/admin/projects/$id',
    path: '/admin/projects/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminGardenNewRoute =
  AuthenticatedAdminGardenNewRouteImport.update({
    id: '/admin/garden/new',
    path: '/admin/garden/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminGardenIdRoute =
  AuthenticatedAdminGardenIdRouteImport.update({
    id: '/admin/garden/$id',
    path: '/admin/garden/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/garden': typeof GardenRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/timeline': typeof TimelineRoute
  '/garden/$slug': typeof GardenSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/garden/': typeof GardenIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/garden/$id': typeof AuthenticatedAdminGardenIdRoute
  '/admin/garden/new': typeof AuthenticatedAdminGardenNewRoute
  '/admin/projects/$id': typeof AuthenticatedAdminProjectsIdRoute
  '/admin/projects/new': typeof AuthenticatedAdminProjectsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/timeline': typeof TimelineRoute
  '/garden/$slug': typeof GardenSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/garden': typeof GardenIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/garden/$id': typeof AuthenticatedAdminGardenIdRoute
  '/admin/garden/new': typeof AuthenticatedAdminGardenNewRoute
  '/admin/projects/$id': typeof AuthenticatedAdminProjectsIdRoute
  '/admin/projects/new': typeof AuthenticatedAdminProjectsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/garden': typeof GardenRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/timeline': typeof TimelineRoute
  '/garden/$slug': typeof GardenSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/garden/': typeof GardenIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/garden/$id': typeof AuthenticatedAdminGardenIdRoute
  '/_authenticated/admin/garden/new': typeof AuthenticatedAdminGardenNewRoute
  '/_authenticated/admin/projects/$id': typeof AuthenticatedAdminProjectsIdRoute
  '/_authenticated/admin/projects/new': typeof AuthenticatedAdminProjectsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contact'
    | '/garden'
    | '/projects'
    | '/timeline'
    | '/garden/$slug'
    | '/projects/$slug'
    | '/garden/'
    | '/projects/'
    | '/admin/'
    | '/admin/garden/$id'
    | '/admin/garden/new'
    | '/admin/projects/$id'
    | '/admin/projects/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contact'
    | '/timeline'
    | '/garden/$slug'
    | '/projects/$slug'
    | '/garden'
    | '/projects'
    | '/admin'
    | '/admin/garden/$id'
    | '/admin/garden/new'
    | '/admin/projects/$id'
    | '/admin/projects/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/contact'
    | '/garden'
    | '/projects'
    | '/timeline'
    | '/garden/$slug'
    | '/projects/$slug'
    | '/garden/'
    | '/projects/'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/garden/$id'
    | '/_authenticated/admin/garden/new'
    | '/_authenticated/admin/projects/$id'
    | '/_authenticated/admin/projects/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  GardenRoute: typeof GardenRouteWithChildren
  ProjectsRoute: typeof ProjectsRouteWithChildren
  TimelineRoute: typeof TimelineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garden': {
      id: '/garden'
      path: '/garden'
      fullPath: '/garden'
      preLoaderRoute: typeof GardenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/garden/': {
      id: '/garden/'
      path: '/'
      fullPath: '/garden/'
      preLoaderRoute: typeof GardenIndexRouteImport
      parentRoute: typeof GardenRoute
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/garden/$slug': {
      id: '/garden/$slug'
      path: '/$slug'
      fullPath: '/garden/$slug'
      preLoaderRoute: typeof GardenSlugRouteImport
      parentRoute: typeof GardenRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/projects/new': {
      id: '/_authenticated/admin/projects/new'
      path: '/admin/projects/new'
      fullPath: '/admin/projects/new'
      preLoaderRoute: typeof AuthenticatedAdminProjectsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/projects/$id': {
      id: '/_authenticated/admin/projects/$id'
      path: '/admin/projects/$id'
      fullPath: '/admin/projects/$id'
      preLoaderRoute: typeof AuthenticatedAdminProjectsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/garden/new': {
      id: '/_authenticated/admin/garden/new'
      path: '/admin/garden/new'
      fullPath: '/admin/garden/new'
      preLoaderRoute: typeof AuthenticatedAdminGardenNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/garden/$id': {
      id: '/_authenticated/admin/garden/$id'
      path: '/admin/garden/$id'
      fullPath: '/admin/garden/$id'
      preLoaderRoute: typeof AuthenticatedAdminGardenIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminGardenIdRoute: typeof AuthenticatedAdminGardenIdRoute
  AuthenticatedAdminGardenNewRoute: typeof AuthenticatedAdminGardenNewRoute
  AuthenticatedAdminProjectsIdRoute: typeof AuthenticatedAdminProjectsIdRoute
  AuthenticatedAdminProjectsNewRoute: typeof AuthenticatedAdminProjectsNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminGardenIdRoute: AuthenticatedAdminGardenIdRoute,
  AuthenticatedAdminGardenNewRoute: AuthenticatedAdminGardenNewRoute,
  AuthenticatedAdminProjectsIdRoute: AuthenticatedAdminProjectsIdRoute,
  AuthenticatedAdminProjectsNewRoute: AuthenticatedAdminProjectsNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface GardenRouteChildren {
  GardenSlugRoute: typeof GardenSlugRoute
  GardenIndexRoute: typeof GardenIndexRoute
}

const GardenRouteChildren: GardenRouteChildren = {
  GardenSlugRoute: GardenSlugRoute,
  GardenIndexRoute: GardenIndexRoute,
}

const GardenRouteWithChildren =
  GardenRoute._addFileChildren(GardenRouteChildren)

interface ProjectsRouteChildren {
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsSlugRoute: ProjectsSlugRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  GardenRoute: GardenRouteWithChildren,
  ProjectsRoute: ProjectsRouteWithChildren,
  TimelineRoute: TimelineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
